# Generated by Django 4.1.7 on 2023-06-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0002_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekplan_task1', to='Programmer.book')),
                ('task2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekplan_task2', to='Programmer.book')),
                ('task3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekplan_task3', to='Programmer.book')),
                ('task4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekplan_task4', to='Programmer.book')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.CharField(max_length=100)),
                ('task2', models.CharField(max_length=100)),
                ('task3', models.CharField(max_length=100)),
                ('task4', models.CharField(max_length=100)),
                ('classday', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmer.book')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmer.day')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmer.weekplan')),
            ],
        ),
    ]
