# Generated by Django 4.1.7 on 2023-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0004_student_weekplan_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplan',
            name='week_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
