# Generated by Django 4.1.7 on 2023-06-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0005_weekplan_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogram',
            name='book',
        ),
    ]
