# Generated by Django 4.1.7 on 2023-06-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0007_alter_dailyprogram_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogram',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programmer.weekplan'),
        ),
    ]
