# Generated by Django 4.1.7 on 2023-06-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0008_alter_dailyprogram_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprogram',
            old_name='week',
            new_name='relatedweek',
        ),
    ]
