# Generated by Django 4.1.7 on 2023-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0011_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(default='https://placehold.co/400x600?text=No+Document', upload_to='docs/'),
        ),
    ]
