# Generated by Django 4.1.7 on 2023-07-11 15:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0012_book_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(default='empty', upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(default='empty'),
        ),
    ]
