# Generated by Django 4.1.7 on 2023-07-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0013_alter_book_description_alter_book_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Refrence',
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(default='empty', upload_to='tracks/')),
                ('refrence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Programmer.refrence')),
            ],
        ),
    ]
