# Generated by Django 4.1.7 on 2023-07-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0014_rename_book_refrence_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefrenceSeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(default='empty', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='refrence',
            name='cover',
            field=models.ImageField(default='empty', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='refrence',
            name='seri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Programmer.refrenceseri'),
        ),
    ]
