# Generated by Django 4.1.7 on 2023-07-15 09:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0015_refrenceseri_alter_refrence_cover_refrence_seri'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrenceseri',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
