# Generated by Django 4.1.7 on 2023-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0016_refrenceseri_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrence',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refrence',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refrence',
            name='related_references',
            field=models.ManyToManyField(blank=True, to='Programmer.refrence'),
        ),
    ]
