# Generated by Django 4.1.7 on 2023-07-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0017_refrence_author_refrence_publisher_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refrence',
            table='Refrence',
        ),
    ]
