# Generated by Django 4.1.7 on 2023-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0019_alter_weekplan_task2_alter_weekplan_task3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrence',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='refrenceseri',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
