# Generated by Django 4.1.7 on 2023-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0020_refrence_slug_refrenceseri_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrence',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
