# Generated by Django 4.1.7 on 2023-07-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0021_alter_refrence_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrence',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
