# Generated by Django 4.1.7 on 2023-07-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0023_category_keyword_language_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrence',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Programmer.category'),
        ),
        migrations.AddField(
            model_name='refrence',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=1, to='Programmer.keyword'),
        ),
        migrations.AddField(
            model_name='refrence',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Programmer.language'),
        ),
        migrations.AddField(
            model_name='refrence',
            name='skill_level',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Programmer.skill_level'),
        ),
    ]
