# Generated by Django 4.1.7 on 2023-07-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0025_category_cover_language_cover_skill_level_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrence',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programmer.category'),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='Programmer.keyword'),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programmer.language'),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programmer.skill_level'),
        ),
    ]
