# Generated by Django 3.2.20 on 2023-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0026_alter_refrence_category_alter_refrence_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrence',
            name='pages',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='refrence',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refrence',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='related_references',
            field=models.ManyToManyField(blank=True, related_name='_Programmer_refrence_related_references_+', to='Programmer.Refrence'),
        ),
    ]
