# Generated by Django 3.2.20 on 2023-10-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0027_auto_20230806_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrence',
            name='isbn',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
