# Generated by Django 3.2.20 on 2023-10-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0028_refrence_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrenceseri',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programmer.refrenceseri'),
        ),
    ]
