# Generated by Django 3.2.20 on 2023-10-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0029_refrenceseri_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrenceseri',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programmer.category'),
        ),
    ]
