# Generated by Django 3.2.20 on 2023-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmer', '0031_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrence',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
